### ISSUE TITLE
New issue....

### ISSUE THREAD

**Issue by Lionharth** [linsomniac/spotify_to_ytmusic#11]
![bild](https://github.com/linsomniac/spotify_to_ytmusic/assets/90109349/fcaa0acb-75ec-489a-bcb1-26a411506569)

**Comment by linsomniac** [comment]
I've pushed a code change that will print more details, but also the line above that is erroring is unused.  Grab the new version please and try that, if it errors out it should give more information about the track that is having problems.

**Comment by Lionharth** [comment]
It wouldn't update via PIP (Sorry I don't use github a lot so I dont really know how it works)

**Comment by linsomniac** [comment]
I didn't publish that change to pip, I'm just publishing it now.  Give it a try, thanks!

**Comment by Lionharth** [comment]
Thanks! I've updated it, and I get the exact same error again (or at least very similar), at the same place.
![bild](https://github.com/linsomniac/spotify_to_ytmusic/assets/90109349/04176f4f-b020-47ab-9c7a-433a25fd2cc8)

**Comment by linsomniac** [comment]
Harumph!  Made a new release, please try that one.

**Comment by linsomniac** [comment]
Interesting...  Do you have any idea what that indicates in that "Spotify track seems to be malformed"?  Is this a reference to a playlist or something else?  I think the fix will be to skip a track if it indicates "None" for the track, but I'd like to understand what it indicates.

Please remove the above image if you have not already, as it includes some potentially PII.

**Comment by Lionharth** [comment]
Thank you so much for helping me, I'm going to try it right now to see if it works! I can't wait to see this project develop more!

**Comment by Lionharth** [comment]
Finally! I've transferred my almost 2000 songs from my playlist to yt music! Thanks!

**Comment by linsomniac** [comment]
Fantastic, thanks for your help in figuring it out!
