### ISSUE TITLE
FR - import liked album

### ISSUE THREAD

**Issue by Vercety87** [linsomniac/spotify_to_ytmusic#13]
Hi,

Would be great to be able to import liked album.

Using this script export all liked album from spotify : [https://github.com/caseychu/spotify-backup/blob/ee062e09de9b36166d7326f851514b6b266a249d/spotify-backup.py](https://github.com/caseychu/spotify-backup/blob/ee062e09de9b36166d7326f851514b6b266a249d/spotify-backup.py)

**Comment by linsomniac** [comment]
I don't understand.  Does a spotify backup contain an album but not the tracks?  Can you give me an example of this, some information on how to create this situation so I can reproduce it?

**Comment by Vercety87** [comment]
No, this is when you liked an album in Spotify, it will be available in your library.

Here an export done with the spotify-backup script supporting albums export.

[playlists.json](https://github.com/linsomniac/spotify_to_ytmusic/files/13998715/playlists.json)

**Comment by linsomniac** [comment]
I think I've got this reproduced and have the information I need to make some progress on it, probably will have something tomorrow or the day after.  It's been a little hard to track down, I ended up having to delete all my liked songs, which had to be done one at a time in Spotify, to get started with a clean slate where I could investigate just having a liked album.

The JSON path for the tracks on a liked album is `playlists_json['albums'][0:len(albums)]['album']['tracks']['items']` -- It is NOT under the `playlists_json['playlists']`

**Comment by linsomniac** [comment]
I believe with this latest version that this is supported.  I'm going to push to pypi so that you can grab the latest version.
