### ISSUE TITLE
Server returned HTTP 401: Unauthorized. You must be signed in to perform this operation. in 5 seconds

### ISSUE THREAD

**Issue by funknsmashu** [linsomniac/spotify_to_ytmusic#141]
I think this is a problem logging in to YouTube. This happens whenever I try to copy playlists or load liked songs. It worked last night, managed to like half my songs then my computer shut off. Now it won't login. I tried the command 'ytmusicapi oath' to reauthorise. Where is the auto login file located so I can delete it? Any ideas? Cheers.
![problem](https://github.com/user-attachments/assets/f289e303-577f-40d2-a4f5-08beffc06df4)

**Comment by ahmadtc1** [comment]
Hey @funknsmashu , facing the same issue. How'd you manage to resolve it?
