### ISSUE TITLE
Unable to add more than around 270 songs before youtube starts refusing requests (HTTP error 400)

### ISSUE THREAD

**Issue by cheesecakegangster** [linsomniac/spotify_to_ytmusic#2]
Using copy_playlist.py.

Re-running the script does not change the outcome, and it does not stop at a specific song. See screenshots.

![image](https://github.com/linsomniac/spotify_to_ytmusic/assets/29154410/94224a8d-c4f6-43a2-a5bc-be2f40c8f9fa)

![image](https://github.com/linsomniac/spotify_to_ytmusic/assets/29154410/ed1192a2-0fb2-45d3-934b-c0498ddf5219)

Adding the ```time.sleep(3)``` here worked to solve that:

```python
for src_track in src_pl["tracks"]:
        time.sleep(3)
```

Takes longer, but at least it completes the playlist.

**Comment by linsomniac** [comment]
I added a per-track sleep, default of a tenth of a second, and a command-line argument to control it.  I also made the retry do a back-off, which might help; first time it fails it sleeps for 5 seconds, then 10, then 20...  Thanks for the feedback!
