### ISSUE TITLE
Setup instructions not clear to me

### ISSUE THREAD

**Issue by szotts** [linsomniac/spotify_to_ytmusic#24]
Hello, I'm new to python and I'm stuck at one of the very first steps in the README file. I've installed the package via pip and wanted to run `python gui.py` but I'm getting "[Errno 2] No such file or directory". I've moved to the directory and tried again and got the same message. What am I doing wrong?

**Comment by Yoween** [comment]
Hello ! The pip implementation is not done yet I believe. If you aim to use the GUI, you'll need to download the .zip file from the `releases` tab.

**Comment by linsomniac** [comment]
This should be resolved now, I've updated the README and have just pushed a new version to the pip servers, so try re-installing via pip and run "s2yt_gui" or "python -m spotify2ytmusic gui"
