### ISSUE TITLE
python3 guy.py

### ISSUE THREAD

**Issue by tommibru** [linsomniac/spotify_to_ytmusic#27]
Hello there, I am trying to use the guy but I keep on running into issues and they are probably due by the fact i'm not a pro at any of this.

I have downloaded the latest version from release and i unzipped it then i cd into the folder and when I try to get to the GUI i get the following error:

Traceback (most recent call last):
  File "/home/parallels/Downloads/spotify_to_ytmusic-0.9.16/spotify2ytmusic/gui.py", line 11, in <module>
    import cli
  File "/home/parallels/Downloads/spotify_to_ytmusic-0.9.16/spotify2ytmusic/cli.py", line 7, in <module>
    from . import backend
ImportError: attempted relative import with no known parent package

I have rebooted the laptop and re tried it but no luck.

**Comment by linsomniac** [comment]
That is an issue the last release, try downloading the latest version and run it with "python -m spotify2ytmusic gui" (see the README for more details).  Let me know if that works better for you.

**Comment by tommibru** [comment]
Worked like a charm, thank you very much.
