### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by slaffcheff** [linsomniac/spotify_to_ytmusic#29]
`$ python3 -m pip install spotify2ytmusic

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement spotify2ytmusic (from versions: none)
ERROR: No matching distribution found for spotify2ytmusic

WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.`

**Comment by slaffcheff** [comment]
`$ s2yt_gui
Traceback (most recent call last):
  File "/opt/homebrew/bin/s2yt_gui", line 5, in <module>
    from spotify2ytmusic.gui import main
  File "/opt/homebrew/lib/python3.11/site-packages/spotify2ytmusic/gui.py", line 8, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'`

**Comment by linsomniac** [comment]
Try "pip install tk" to get past that last error.  I'll add that to the requirements and documentation.

For the first one, are you running on MacOS?  Where is your Python interpreter from, brew?

**Comment by Yoween** [comment]
If you are using Linux, you may not have tkinter installed. To install it, you need to find your python version, by typing `python3 -V` in a terminal. For example, mine is `3.10.2`, so I typed `sudo apt-get install python3.10-tk`. If you have `3.6`, you install `3.6-tk`, etc...

**Comment by slaffcheff** [comment]
I am on macOS Sonoma 14.2.1 (23C71). Will try the TK advise and will update here.

**Comment by linsomniac** [comment]
@slaffcheff On my MacOS Sonoma 14.2.1, if I do `which python3`, it says: `/opt/homebrew/bin/python3`.  If I then run `python3 -m pip install spotify2ytmusic` it seems to install correctly, and I can then run `ytmusicapi oauth`, etc...

**Comment by linsomniac** [comment]
@Yoween: You probably don't need to know the version for Linux install, on Ubuntu you can do "apt install python3-tk" which is a virtual package that picks up the right version.

**Comment by slaffcheff** [comment]
I managed to start it but after I create backup and try login to youtube music it goes to backup tab and says "backup is required". I enter a loop ..

**Comment by Yoween** [comment]
> @Yoween: You probably don't need to know the version for Linux install, on Ubuntu you can do "apt install python3-tk" which is a virtual package that picks up the right version.

Oh well that's good to know, thanks!

**Comment by Yoween** [comment]
> I managed to start it but after I create backup and try login to youtube music it goes to backup tab and says "backup is required". I enter a loop ..

Can you tell me in detail what you did for this to happen ? Because for me it works fine...

**Comment by rustamgaifullin** [comment]
Hello, 

I just to want to add what I did, in order to fix the error in the Mac OS. 
I think, by default, if you install python using brew, you also need to run 
`brew install python-tk`
Hope it helps for anyone, who experienced similar issue.

**Comment by linsomniac** [comment]
Thanks, included in the instructions!

**Comment by S1M0N38** [comment]
I had the same issue running Python installed with brew. However, I've solved it using [uv](https://docs.astral.sh/uv/).

1. Install uv
2. Install Python using uv
3. git clone spotify_to_ytmusic and cd into it
4. Create a virtual environment using uv: `uv venv`
5. Activate the environment: `source .venv/bin/activate`
6. Install dependencies: `﻿uv pip install ytmusicapi tk`
7. Follow the rest of the readme

---

I'm commenting here with an alternative to get a working installation of spotify_to_ytmusic for those who encounter the tk issue.

**Comment by tobyhinloopen** [comment]
For macOS users that stumble on this error:

```sh
brew install python-tk
which python3 # should be /opt/homebrew/bin/python3 
rm -rf .venv
python3 -m venv .venv # or /opt/homebrew/bin/python3  -m venv .venc 
source .venv/bin/activate
pip install ytmusicapi tk
```
