### ISSUE TITLE
copy_playlist.py does not copy every song in playlist and doesn't report an error either

### ISSUE THREAD

**Issue by cheesecakegangster** [linsomniac/spotify_to_ytmusic#3]
I made a script (that is, ChatGPT did) to count the number of songs in the playlist to verify ```spotify-backup.py``` is counting correctly, and the number is correct (906 in my case). The script has only copied 863 songs and has not once reported not being able to find a song. 

Counting script for reference:

```python
import json

# Function to count songs in each playlist
def count_songs_in_playlists(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
        
        # Dictionary to store the count of songs for each playlist
        song_counts = {}

        # Iterate through each playlist and count the songs
        for playlist in data['playlists']:
            playlist_name = playlist['name']
            number_of_songs = len(playlist['tracks'])
            song_counts[playlist_name] = number_of_songs

        return song_counts

# Path to the JSON file
file_path = 'playlists.json'

# Counting songs in each playlist
song_counts = count_songs_in_playlists(file_path)
print(song_counts)```

**Comment by linsomniac** [comment]
Can I include this code for others to use?

I've also modified `copy_playlist` to look for duplicates in the tracks it is adding, and report how many unique tracks were added and how many were duplicates.  It is also flagging duplicates in the output.

My guess is that you have some similar tracks in spotify that the search is finding the same track in Youtube, so those are being collapsed.  Like if on Spotify you had "Only You" from the Yaz album Upstairs at Eric's, and also "Only You" from the Yazoo album Upstairs at Eric's, and also "Only You by Yaz" from the album Greatest Hits of '80s...  Which maybe YTMusic detects all of these as the same song in their collection?

I spot checked the choices it was making in converting my playlist over and all of the choices I looked at seemed good.  But there might be some corner cases where it does wrong.  I'd be interested in those and ideas on how to fix those, but so far I haven't found any of them.

Maybe these code changes will find some in your library?  Or maybe I'm totally wrong in my guess and the problem lies elsewhere?

**Comment by linsomniac** [comment]
I re-ran one of my biggest uploads with the new code, and it reported 26 duplicates and added 1268 tracks.  I did a spot check of 4 of those and it looks like I'm running into exactly the sort of situation I mentioned:

Spotify:   If I Had A Rocket Launcher - Bruce Cockburn - Stealing Fire
 Youtube: If I Had A Rocket Launcher - Bruce Cockburn - Stealing Fire
Spotify:   If I Had A Rocket Launcher - Bruce Cockburn - Stealing Fire (Deluxe Edition)
 Youtube: If I Had A Rocket Launcher - Bruce Cockburn - Stealing Fire
(DUPLICATE, this track has already been added)
Spotify:   Let The Day Begin - The Call - Let The Day Begin
 Youtube: Let The Day Begin - The Call - Let The Day Begin
Spotify:   Let the Day Begin - Michael Been AKA The Call - The Best Of The Call
 Youtube: Let The Day Begin - The Call - {'name': 'Let The Day Begin', 'id': 'MPREb_vWAX2F2h1Ty'}
(DUPLICATE, this track has already been added)
Spotify:   Everybody Wants You - Billy Squier - Emotions In Motion
 Youtube: Everybody Wants You - Billy Squier - Emotions In Motion
Spotify:   Everybody Wants You - Billy Squier - Absolute Hits
 Youtube: Everybody Wants You - Billy Squier - {'name': 'Emotions In Motion', 'id': 'MPREb_DQal0TQ0MXx'}
(DUPLICATE, this track has already been added)

**Comment by cheesecakegangster** [comment]
> Can I include this code for others to use?

Of course!

I ChatGPT'd another script to verify how many duplicates are in the original json dump from spotify; sure enough: "Total duplicate songs: 40", so that would bring the real total down to 866. That means I'm only missing 3 songs, but I think I can live with that haha

```python
import json


# Path to the JSON file
JSON_FILE_PATH = 'playlists.json'
PLAYLIST_NAME = "DUSAN'S MAD PLAYLIST"


# Load songs from the specified playlist in playlists.json and check for exact duplicates
def find_duplicate_songs(file_path, playlist_name):
    with open(file_path, 'r') as file:
        data = json.load(file)

        # Extracting song names from the specified playlist
        song_names = []
        for playlist in data['playlists']:
            if playlist['name'] == playlist_name:
                song_names = [track['track']['name'].lower() for track in playlist['tracks']]
                break

        # Finding duplicates and their counts
        duplicates = {}
        for song in song_names:
            if song in duplicates:
                duplicates[song] += 1
            else:
                duplicates[song] = 1

        # Filtering out songs that are not duplicates
        duplicates = {song: count for song, count in duplicates.items() if count > 1}
        return duplicates


# Finding duplicates in the specified playlist
duplicate_songs = find_duplicate_songs(JSON_FILE_PATH, PLAYLIST_NAME)

total_duplicates = sum(count - 1 for count in duplicate_songs.values())  # Subtracting 1 as the original song is not a duplicate

if duplicate_songs:
    print(f"Duplicate songs found in '{PLAYLIST_NAME}':")
    for song, count in duplicate_songs.items():
        print(f"'{song}': {count} times")
    print(f"Total duplicate songs: {total_duplicates}")
else:
    print(f"No duplicate songs found in '{PLAYLIST_NAME}'.")
```

**Comment by cheesecakegangster** [comment]
```python
import json
from fuzzywuzzy import fuzz
from collections import defaultdict

# Group songs by their first few characters to reduce comparisons
def group_songs(songs, group_size=3):
    grouped_songs = defaultdict(list)
    for song in songs:
        key = song[:group_size]  # Group by the first few characters
        grouped_songs[key].append(song)
    return grouped_songs

# Function to find approximate duplicates within groups
def find_approximate_duplicates(grouped_songs, threshold=85):
    duplicates = defaultdict(int)
    paired_songs = set()  # Keep track of pairs that have been matched

    for group in grouped_songs.values():
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                pair = tuple(sorted([group[i], group[j]]))
                if pair not in paired_songs and fuzz.ratio(group[i], group[j]) > threshold:
                    duplicates[group[i]] += 1
                    duplicates[group[j]] += 1
                    paired_songs.add(pair)
                    # Enhanced logging for matched pairs
                    if 'war' in pair or 'war?' in pair:
                        print(f"Matched pair: '{group[i]}' and '{group[j]}'")  # Print out matched pairs involving 'war' or 'war?'

    return duplicates

# Function to load songs from the specified playlist in playlists.json and check for approximate duplicates
def find_duplicate_songs(file_path, playlist_name):
    with open(file_path, 'r') as file:
        data = json.load(file)

        # Extracting song names from the specified playlist
        song_names = []
        for playlist in data['playlists']:
            if playlist['name'] == playlist_name:
                song_names = [track['track']['name'].lower().strip() for track in playlist['tracks']]
                break

        # Group songs to reduce comparisons
        grouped_songs = group_songs(song_names)

        # Finding approximate duplicates
        return find_approximate_duplicates(grouped_songs)

# Path to the JSON file
json_file_path = 'playlists.json'
playlist_name = "DUSAN'S MAD PLAYLIST"

# Finding duplicates in the specified playlist
duplicate_songs = find_duplicate_songs(json_file_path, playlist_name)

total_approximate_duplicates = sum(duplicate_songs.values())

if duplicate_songs:
    print(f"\nApproximate duplicate songs found in '{playlist_name}':")
    for song, count in duplicate_songs.items():
        print(f"'{song}': {count} times")
    print(f"\nTotal approximate duplicate songs: {total_approximate_duplicates // 2}")  # Dividing by 2 as each duplicate is counted twice
else:
    print(f"No approximate duplicate songs found in '{playlist_name}'.")
```
