### ISSUE TITLE
[GUI Version] Failed to run "Load liked songs" step

### ISSUE THREAD

**Issue by vkawai** [linsomniac/spotify_to_ytmusic#30]
Installed this script through PIP, and ran the GUI command. Currently running into the following runtime error:
```
TypeError: Window.__init__.<locals>.<lambda>() missing 1 required positional argument: 'x'
Exception in Tkinter callback
Traceback (most recent call last):
  File <APP_DATA_PATH>\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
```

**Comment by linsomniac** [comment]
@Yoween Does this mean anything to you?

**Comment by vkawai** [comment]
https://github.com/linsomniac/spotify_to_ytmusic/blob/d80a222f8a516d1416f9708c0b798ba371d84d25/spotify2ytmusic/gui.py#L157

Removed the `x` from the lambda function, and it worked here.

**Comment by Yoween** [comment]
It looks like I forgot to change that line, good catch! I have a few things to fix and I'll upload the changes

**Comment by wizzer129** [comment]
siiick, I had the same issues appreciate the support

**Comment by vkawai** [comment]
@Yoween When I was messing with the file to see if this change works or not, I noticed that there are another `lambda x` in the same function body. Might be a good idea to check the other line

**Comment by linsomniac** [comment]
Going to push out a new version with this fix in it in ~2 minutes.
