### ISSUE TITLE
 Trying again... Couldn't load URL: https://api.spotify.com/v1/me (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>)

### ISSUE THREAD

**Issue by charindithjaindu** [linsomniac/spotify_to_ytmusic#38]
I am getting errored after login into spotify.
<img width="875" alt="image" src="https://github.com/linsomniac/spotify_to_ytmusic/assets/75799963/c266b6c8-f2f7-4383-a898-a72785c27549">

**Comment by kiranmuddam** [comment]
@charindithjaindu @linsomniac https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

**Comment by evanwon** [comment]
The suggestion from @kiranmuddam worked for me on macOS (thank you!).

Specifically: https://stackoverflow.com/a/53310545

And to save you a click:

> If you're using macOS go to Macintosh HD > Applications > Python3.X folder (or whatever version of python you're using) > double click on "Install Certificates.command" file.

**Comment by linsomniac** [comment]
This is probably resolved by #58 please see that issue and run the command there to resolve it.

**Comment by onatsubasi** [comment]
How do I resolve this in windows?
