### ISSUE TITLE
ERROR: No matching distribution found for spotify2ytmusic

### ISSUE THREAD

**Issue by Besh-afk** [linsomniac/spotify_to_ytmusic#39]
hey im not really sure what this means but i gegt this error and cant move forward 
<img width="1440" alt="Screenshot 2024-02-19 at 4 51 03 PM" src="https://github.com/linsomniac/spotify_to_ytmusic/assets/97922088/8dfd5703-793b-4528-8595-0c63d9e47767">

**Comment by linsomniac** [comment]
I presume you are running "pip install spotify2ytmusic"?  What does "pip --version" report?

**Comment by thevisheshone** [comment]
I'm seeing the same issue on my Mac (I don't usually work with python, and I just had to install it on this Mac)
I've had to use pip3 instead of pip. pip3 -V gives me: `pip 24.0 from <path in Library/Python/3.9/lib/python/site-packages/pip>`

**Comment by thevisheshone** [comment]
Okay, just had to update python to 3.10, not sure why it didn't automatically get the latest. 
@Besh-afk 
`brew install python@3.10`
`brew install python-tk@3.10`
`pip3.10 install spotify2ytmusic`

**Comment by Besh-afk** [comment]
Hey thank you!!! I was already running python 3.11. I'm not sure why but `pip3.11 install spotify2ytmusic` worked.  thanks for helping me out!!

**Comment by linsomniac** [comment]
Nice work on tracking this down!  I've added this into the FAQ.

**Comment by maqtim** [comment]
> Nice work on tracking this down! I've added this into the FAQ.

After some headscratching....Life saver addition to the FAQ!

**Comment by maqtim** [comment]
After some headscratching....Life saver addition to the FAQ!
