### ISSUE TITLE
"Requested entity was not found"

### ISSUE THREAD

**Issue by CyanideLion** [linsomniac/spotify_to_ytmusic#4]
Hi, I get this error from time to time which causes the copying to stop, I don't know if that's a known issue but I wanted to bring it to your attention:

```
Traceback (most recent call last):
  File "C:\path_to_file\load_liked", line 60, in <module>
    dst_track = lookup_song(yt, src_track_name, src_track_artist, src_album_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\path_to_file\load_liked", line 22, in lookup_song
    for track in yt.get_album(album["browseId"])["tracks"]:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\ytmusicapi\mixins\browsing.py", line 429, in get_album
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\ytmusicapi\ytmusic.py", line 238, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.
```

**Comment by linsomniac** [comment]
That sounds like there is an album that YTMusic is returning a reference to, but then when it is requested it is not there, that's the 404 error.  I've pushed a couple changes to the code, it'll now continue the load if that happens and report that there were errors, but it'll also try looking at the next couple albums if the first gets a 404, but then will also try doing a straight song lookup.

Give that a shot and let me know how it looks.

**Comment by CyanideLion** [comment]
Looks good, tried it now and I didn't get any error messages and it completed. Thank you!
