### ISSUE TITLE
Unable to sign into YT music

### ISSUE THREAD

**Issue by nynnji** [linsomniac/spotify_to_ytmusic#41]
When trying to use the GUI to login to YT Music, opening it I see the message "No file detected. Manual login required," and then when using `ytmusicapi oauth` in PowerShell, it says it isn't recognized. The same happens when using `s2yt_gui` 
I don't really know what might have went wrong because I've never done anything like this, but I got to the GUI using the `python -m spotify2ytmusic gui` command so I don't know what went wrong in the install.

**Comment by linsomniac** [comment]
I've just pushed a new version, 0.9.20, which gives you several ways to run ytmusicapi.  Since "python -m spotify2ytmusic gui" seems to work for you, try doing "pip install --upgrade spotify2ytmusic", and then: "python -m spotify2ytmusic ytoauth" to run it.

**Comment by linsomniac** [comment]
Another possibility to try is: I have not tested this at all, but I've taken a stab at creating an installer for Windows, you can try it here: https://github.com/linsomniac/spotify_to_ytmusic/releases/tag/0.9.20

**Comment by nynnji** [comment]
Everything worked with the new version and new command, but I'm having an issue copying a playlist that was recently created. It never adds any songs to the playlist, or if the YT playlist ID isn't entered, it never creates one. Besides this playlist, every other playlist copied fine.
