### ISSUE TITLE
Could not find spotify playlist None

### ISSUE THREAD

**Issue by archief1878** [linsomniac/spotify_to_ytmusic#49]
ValueError: Could not find Spotify playlist None

Keep getting this error message when trying to import the liked songs onto YT music.

**Comment by linsomniac** [comment]
What command did you use to export the Spotify playlist, and can you provide more of the traceback than just the error above?  My guess is that the Spotify exported playlist file does not include the "liked" songs (not sure how that would have happened), the "None" playlist is the liked songs.

**Comment by archief1878** [comment]
Hi there,

I managed to solve the problem eventually I just had to keep trying
combinations of things and commands. My main struggle was that I run python
through VS code and couldn't get the GUI to work. The steps suggested for
going down the GUI route didn't work so I ended up having to run everything
through command prompt and doing it that way. It worked eventually but the
steps weren't really clear for my particular situation that's all.
