### ISSUE TITLE
Creating playlist when copying

### ISSUE THREAD

**Issue by CyanideLion** [linsomniac/spotify_to_ytmusic#5]
It'd be nice to be able to make the ytmusic_playlist_id in the copy_playlist() function optional, with it being able to create a new playlist if no existing ID is given. It annoyed me always having to create a playlist before copying into it:D

I tried implementing that myself but I can't create a pull request (that might be on me tho, it's my first time working on GitHub and I'm fairly new to programming). Please be nice if this is too messy:D

```
 if args.ytmusic_playlist_id is None:
        pl_name = input("What is the name of the new playlist?\n")
        dst_pl_id = YTMusic("oauth.json").create_playlist(title=pl_name, description=pl_name)
    else:
        dst_pl_id = args.ytmusic_playlist_id
```

**Comment by linsomniac** [comment]
Here is some information about creating a PR:  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

In short: You'll want to create a fork of the repo (from my repo page), then clone your fork, create a branch ("git branch create-when-copy") and switch to it ("git switch create-when-copy").  Make your changes and then commit/push.  Go back to github.com on your fork, and it'll ask if you want to create a PR.

**Comment by linsomniac** [comment]
Thank you for the contribution!
