### ISSUE TITLE
ERROR: No file 'oauth.json'

### ISSUE THREAD

**Issue by Santamoo** [linsomniac/spotify_to_ytmusic#57]
I keep trying to login but whenever i get to load liked songs its keeps saying ERROR: No file 'oauth.json' exists in the current directory.
       Have you logged in to YTMusic?  Run 'ytmusicapi oauth' to login. i have tried to log in multiple times as well as tryed to use the command in cmd. please help

**Comment by Santamoo** [comment]
i also looked through the files and it seems as if there is no oauth.json

**Comment by Santamoo** [comment]
i figured it out and had to install java

**Comment by Jyzeff** [comment]
how did you figured it out?

**Comment by linsomniac** [comment]
May be related to #60
