### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED on MacOS

### ISSUE THREAD

**Issue by omarsinno54** [linsomniac/spotify_to_ytmusic#58]
Hello,

I think it's important to mention that for MacOS users, the Python certificates must be downloaded in order to be able to follow the tutorial. 

It's done by doing the following:

Macintosh HD > Applications > Python Folder > double click on "Install Certificates.command" file.

Afterwards, MacOS users can proceed with the tutorial.

**Comment by Velt1** [comment]
Thank you that helped me!

**Comment by linsomniac** [comment]
Thank you, I've added that to the installation section of the README.
