### ISSUE TITLE
No file 'oauth.json' exists in the current directory.

### ISSUE THREAD

**Issue by Jyzeff** [linsomniac/spotify_to_ytmusic#59]
First, I open the gui and press login. After the login is completed, I press enter and then ctrl-c. but I still encounter "No file 'oauth.json' exists in the current directory." error in gui

**Comment by Jyzeff** [comment]
also there is no file called oauth.json on my computer.

**Comment by linsomniac** [comment]
Try manually running "ytmusicapi oauth" from the command-line, that should create the "oauth.json" file if the login is successful.  If that succeeds, then try running the GUI, it will skip the login step if the file exists.  May be related to #60

**Comment by linsomniac** [comment]
I'm going to close this so that we don't have multiple "ytmusicapi oauth" related tickets all open at once.
