### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Lydrix** [linsomniac/spotify_to_ytmusic#6]
When i use the load liked command i get errors saying that something isn't correct in some lines

**Comment by linsomniac** [comment]
I will need the exact text of the errors to provide help.

Thanks!

**Comment by Yogarpg** [comment]
> I get the same error. Downloaded spotify playlists and authorized through youtube music, then running s2yt_load_liked:
> 
> ```
> Traceback (most recent call last):
> File "<frozen runpy>", line 198, in _run_module_as_main  
> 	File "<frozen runpy>", line 88, in _run_code                                                                                                              
> 	File "C:\Users\MyUser\AppData\Roaming\Python\Python312\Scripts\s2yt_list_playlists.exe\__main__.py", line 7, in <module>                            
> 	File "C:\Users\MyUser\AppData\Roaming\Python\Python312\site-packages\spotify2ytmusic\cli.py", line 16, in list_playlists        
> 	^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\MyUser\AppData\Roaming\Python\Python312\site-packages\ytmusicapi\ytmusic.py", line 130, in __init__
>     input_json = json.loads(auth_str)
>                  ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\Python312\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\Python312\Lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\Python312\Lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

Same here

**Comment by Lydrix** [comment]
> I will need the exact text of the errors to provide help. Copy and paste of the full error or a screen shot will do.
> 
> Thanks!

Same Error as the ones posted above

**Comment by Yogarpg** [comment]
Works for me now, I did everything in the same folder on the same drive and it worked.

**Comment by CyanideLion** [comment]
@Lydrix @sondr
Did you make sure you execute the application in the folder where the .json files (playlists.json and oauth.json) are located?

**Comment by sondr** [comment]
> @Lydrix @sondr Did you make sure you execute the application in the folder where the .json files (playlists.json and oauth.json) are located?

Copying the oauth.json into the working folder worked. playlists.json was already there. Thank you!

**Comment by linsomniac** [comment]
Sorry for the delay in digging into this, folks.  Looks like the issue was not having the "oauth.json" in the directory you're running it, as mentioned above by @CyanideLion .

I've enhanced the code now so that it reports this situation more clearly:

```bash
[N] (spotify2ytmusic-py3.10) sean@seans-laptop ~/p/spotify_to_ytmusic (main) [1]> s2yt_list_playlists
ERROR: No file 'oauth.json' exists in the current directory.
       Have you logged in to YTMusic?  Run 'ytmusicapi oauth' to login
[I] (spotify2ytmusic-py3.10) sean@seans-laptop ~/p/spotify_to_ytmusic (main) [1]> touch oauth.json
[N] (spotify2ytmusic-py3.10) sean@seans-laptop ~/p/spotify_to_ytmusic (main)> s2yt_list_playlists
ERROR: JSON Decode error while trying start YTMusic: Expecting value: line 1 column 1 (char 0)
       This typically means a problem with a 'oauth.json' file.
       Have you logged in to YTMusic?  Run 'ytmusicapi oauth' to login
```

Thanks for reporting this, let me know if there are further issues with this.
