### ISSUE TITLE
Logging in to YT TV instead of YT Music

### ISSUE THREAD

**Issue by J-Davis21** [linsomniac/spotify_to_ytmusic#76]
When using either the GUI, or the CLI ytmusicapi oauth option - it's logging me into YT TV instead of YT Music. There's a few people in the Reddit thread with the same issue. I cannot get this to login to YT Music at all.
![YT Music login issue](https://github.com/linsomniac/spotify_to_ytmusic/assets/95693349/8612468a-68df-4920-b7fe-c2c5ae23396a)

**Comment by mmhood1** [comment]
Experiencing the same issue atm. Staying tuned for a fix.

**Comment by kyu-ra** [comment]
I'm having the same issue

**Comment by linsomniac** [comment]
Note it says "YouTube on TV", not "YouTube TV".  This is not a problem, you can continue on and it will pull your music playlists.

The API that is being used to access YouTube Music (via the "ytmusicapi" library), identifies itself as "YouTube on TV", like if you were connecting a TV to your YouTube account, and then using it to play music.
